# Generated by Django 3.2.5 on 2021-08-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
    ]
