# Generated by Django 3.2.5 on 2021-07-10 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('birthplace', models.CharField(max_length=100, verbose_name='Birthplace')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Group')),
                ('parents', models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parents')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'db_table': 'child',
            },
        ),
    ]
