# Generated by Django 3.2.5 on 2021-08-15 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subject',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_menu', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Week Menu',
                'verbose_name_plural': 'Week Menu',
                'db_table': 'week_menu',
            },
        ),
        migrations.CreateModel(
            name='MealMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.IntegerField(choices=[(1, 'Breakfast'), (2, 'Brunch'), (3, 'Lunch'), (4, 'Tea')], verbose_name='Meal')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day')),
                ('food', models.CharField(max_length=100, verbose_name='Food')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_menu', to='education.weekmenu', verbose_name='Week')),
            ],
            options={
                'verbose_name': 'Meal Menu',
                'verbose_name_plural': 'Meal Menu',
                'db_table': 'meal_menu',
                'ordering': ['meal'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date last updated')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('mother_name', models.CharField(max_length=50, verbose_name='Mother name')),
                ('father_name', models.CharField(max_length=50, verbose_name='Father name')),
                ('birthplace', models.CharField(max_length=100, verbose_name='Birthplace')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Group')),
                ('parents', models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Parents')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('message', models.CharField(blank=True, max_length=250, verbose_name='Message')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organization.organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'db_table': 'activity',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(check=models.Q(('start_time__lte', django.db.models.expressions.F('end_time'))), name='correct_start_end_time'),
        ),
    ]
