# Generated by Django 3.2.5 on 2021-08-17 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='child',
            table=None,
        ),
        migrations.AlterModelTable(
            name='mealmenu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
        migrations.AlterModelTable(
            name='weekmenu',
            table=None,
        ),
    ]
