# Generated by Django 3.2.5 on 2021-08-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20210710_1816'),
        ('education', '0002_auto_20210801_1859'),
    ]

    operations = [
    ]
