# Generated by Django 3.2.5 on 2021-08-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_table'),
        ('authentication', '0002_alter_user_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='organization.organization'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
